apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-web-app
  template:
    metadata:
      labels:
        app: basic-web-app
    spec:
      containers:
      - name: basic-web-app
        image: your-dockerhub-username/basic-web-app:latest
        ports:
        - containerPort: 80
